### ISSUE TITLE
42804: structure of query does not match function result type

### ISSUE THREAD

**Issue by fathonir** [fathonir/pkm#39]
```
    Exception type: PostgresException 
    Exception message: 42804: structure of query does not match function result type
   at pkmLibs.Database.FetchDataTable(String strSQL, DataTable& theDataTable) in C:\Users\Fathoni\source\repos\simbelmawa-webform\pkmLibs\Database.cs:line 95
   at pkm.Cores.pesan.getRowInbox(DataTable& dataTable, Guid idPesan) in C:\Users\Fathoni\source\repos\simbelmawa-webform\pkm\Cores\pesan.cs:line 119
   at pkm.Pages.pesan.bacaPesan.Refresh() in C:\Users\Fathoni\source\repos\simbelmawa-webform\pkm\Pages\Pesan\bacaPesan.ascx.cs:line 72
   at pkm.Pages.pesan.pesanPersonal.lvOutbox_ItemUpdating(Object sender, ListViewUpdateEventArgs e) in C:\Users\Fathoni\source\repos\simbelmawa-webform\pkm\Pages\Pesan\pesanPersonal.ascx.cs:line 467
   at System.Web.UI.WebControls.ListView.HandleUpdate(ListViewItem item, Int32 itemIndex, Boolean causesValidation)
   at System.Web.UI.WebControls.ListView.HandleEvent(EventArgs e, Boolean causesValidation, String validationGroup)
   at System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args)
   at System.Web.UI.WebControls.ListViewDataItem.OnBubbleEvent(Object source, EventArgs e)
   at System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

**Comment by fathonir** [comment]
Fungsi dalam db sudah diperbaiki
